/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the ListDatabaseRoleGrantsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatabaseRoleGrantsResponse{}

// ListDatabaseRoleGrantsResponse struct for ListDatabaseRoleGrantsResponse
type ListDatabaseRoleGrantsResponse struct {
	Grants []RoleGrantDetail `json:"grants,omitempty"`
}

// NewListDatabaseRoleGrantsResponse instantiates a new ListDatabaseRoleGrantsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDatabaseRoleGrantsResponse() *ListDatabaseRoleGrantsResponse {
	this := ListDatabaseRoleGrantsResponse{}
	return &this
}

// NewListDatabaseRoleGrantsResponseWithDefaults instantiates a new ListDatabaseRoleGrantsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDatabaseRoleGrantsResponseWithDefaults() *ListDatabaseRoleGrantsResponse {
	this := ListDatabaseRoleGrantsResponse{}
	return &this
}

// GetGrants returns the Grants field value if set, zero value otherwise.
func (o *ListDatabaseRoleGrantsResponse) GetGrants() []RoleGrantDetail {
	if o == nil || IsNil(o.Grants) {
		var ret []RoleGrantDetail
		return ret
	}
	return o.Grants
}

// GetGrantsOk returns a tuple with the Grants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDatabaseRoleGrantsResponse) GetGrantsOk() ([]RoleGrantDetail, bool) {
	if o == nil || IsNil(o.Grants) {
		return nil, false
	}
	return o.Grants, true
}

// HasGrants returns a boolean if a field has been set.
func (o *ListDatabaseRoleGrantsResponse) HasGrants() bool {
	if o != nil && !IsNil(o.Grants) {
		return true
	}

	return false
}

// SetGrants gets a reference to the given []RoleGrantDetail and assigns it to the Grants field.
func (o *ListDatabaseRoleGrantsResponse) SetGrants(v []RoleGrantDetail) {
	o.Grants = v
}

func (o ListDatabaseRoleGrantsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatabaseRoleGrantsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Grants) {
		toSerialize["grants"] = o.Grants
	}
	return toSerialize, nil
}

type NullableListDatabaseRoleGrantsResponse struct {
	value *ListDatabaseRoleGrantsResponse
	isSet bool
}

func (v NullableListDatabaseRoleGrantsResponse) Get() *ListDatabaseRoleGrantsResponse {
	return v.value
}

func (v *NullableListDatabaseRoleGrantsResponse) Set(val *ListDatabaseRoleGrantsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatabaseRoleGrantsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatabaseRoleGrantsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatabaseRoleGrantsResponse(val *ListDatabaseRoleGrantsResponse) *NullableListDatabaseRoleGrantsResponse {
	return &NullableListDatabaseRoleGrantsResponse{value: val, isSet: true}
}

func (v NullableListDatabaseRoleGrantsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatabaseRoleGrantsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


