/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the ChangeRoleGrantRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeRoleGrantRequest{}

// ChangeRoleGrantRequest struct for ChangeRoleGrantRequest
type ChangeRoleGrantRequest struct {
	RoleName *string `json:"roleName,omitempty"`
	Privilege *string `json:"privilege,omitempty"`
	WithGrant *bool `json:"withGrant,omitempty"`
}

// NewChangeRoleGrantRequest instantiates a new ChangeRoleGrantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeRoleGrantRequest() *ChangeRoleGrantRequest {
	this := ChangeRoleGrantRequest{}
	return &this
}

// NewChangeRoleGrantRequestWithDefaults instantiates a new ChangeRoleGrantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeRoleGrantRequestWithDefaults() *ChangeRoleGrantRequest {
	this := ChangeRoleGrantRequest{}
	return &this
}

// GetRoleName returns the RoleName field value if set, zero value otherwise.
func (o *ChangeRoleGrantRequest) GetRoleName() string {
	if o == nil || IsNil(o.RoleName) {
		var ret string
		return ret
	}
	return *o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeRoleGrantRequest) GetRoleNameOk() (*string, bool) {
	if o == nil || IsNil(o.RoleName) {
		return nil, false
	}
	return o.RoleName, true
}

// HasRoleName returns a boolean if a field has been set.
func (o *ChangeRoleGrantRequest) HasRoleName() bool {
	if o != nil && !IsNil(o.RoleName) {
		return true
	}

	return false
}

// SetRoleName gets a reference to the given string and assigns it to the RoleName field.
func (o *ChangeRoleGrantRequest) SetRoleName(v string) {
	o.RoleName = &v
}

// GetPrivilege returns the Privilege field value if set, zero value otherwise.
func (o *ChangeRoleGrantRequest) GetPrivilege() string {
	if o == nil || IsNil(o.Privilege) {
		var ret string
		return ret
	}
	return *o.Privilege
}

// GetPrivilegeOk returns a tuple with the Privilege field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeRoleGrantRequest) GetPrivilegeOk() (*string, bool) {
	if o == nil || IsNil(o.Privilege) {
		return nil, false
	}
	return o.Privilege, true
}

// HasPrivilege returns a boolean if a field has been set.
func (o *ChangeRoleGrantRequest) HasPrivilege() bool {
	if o != nil && !IsNil(o.Privilege) {
		return true
	}

	return false
}

// SetPrivilege gets a reference to the given string and assigns it to the Privilege field.
func (o *ChangeRoleGrantRequest) SetPrivilege(v string) {
	o.Privilege = &v
}

// GetWithGrant returns the WithGrant field value if set, zero value otherwise.
func (o *ChangeRoleGrantRequest) GetWithGrant() bool {
	if o == nil || IsNil(o.WithGrant) {
		var ret bool
		return ret
	}
	return *o.WithGrant
}

// GetWithGrantOk returns a tuple with the WithGrant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChangeRoleGrantRequest) GetWithGrantOk() (*bool, bool) {
	if o == nil || IsNil(o.WithGrant) {
		return nil, false
	}
	return o.WithGrant, true
}

// HasWithGrant returns a boolean if a field has been set.
func (o *ChangeRoleGrantRequest) HasWithGrant() bool {
	if o != nil && !IsNil(o.WithGrant) {
		return true
	}

	return false
}

// SetWithGrant gets a reference to the given bool and assigns it to the WithGrant field.
func (o *ChangeRoleGrantRequest) SetWithGrant(v bool) {
	o.WithGrant = &v
}

func (o ChangeRoleGrantRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeRoleGrantRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoleName) {
		toSerialize["roleName"] = o.RoleName
	}
	if !IsNil(o.Privilege) {
		toSerialize["privilege"] = o.Privilege
	}
	if !IsNil(o.WithGrant) {
		toSerialize["withGrant"] = o.WithGrant
	}
	return toSerialize, nil
}

type NullableChangeRoleGrantRequest struct {
	value *ChangeRoleGrantRequest
	isSet bool
}

func (v NullableChangeRoleGrantRequest) Get() *ChangeRoleGrantRequest {
	return v.value
}

func (v *NullableChangeRoleGrantRequest) Set(val *ChangeRoleGrantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeRoleGrantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeRoleGrantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeRoleGrantRequest(val *ChangeRoleGrantRequest) *NullableChangeRoleGrantRequest {
	return &NullableChangeRoleGrantRequest{value: val, isSet: true}
}

func (v NullableChangeRoleGrantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeRoleGrantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


