/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateServiceAccountCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateServiceAccountCredentialRequest{}

// CreateServiceAccountCredentialRequest struct for CreateServiceAccountCredentialRequest
type CreateServiceAccountCredentialRequest struct {
	Name *string `json:"name,omitempty"`
	RoleId *string `json:"roleId,omitempty"`
}

// NewCreateServiceAccountCredentialRequest instantiates a new CreateServiceAccountCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateServiceAccountCredentialRequest() *CreateServiceAccountCredentialRequest {
	this := CreateServiceAccountCredentialRequest{}
	return &this
}

// NewCreateServiceAccountCredentialRequestWithDefaults instantiates a new CreateServiceAccountCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateServiceAccountCredentialRequestWithDefaults() *CreateServiceAccountCredentialRequest {
	this := CreateServiceAccountCredentialRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateServiceAccountCredentialRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServiceAccountCredentialRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateServiceAccountCredentialRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateServiceAccountCredentialRequest) SetName(v string) {
	o.Name = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *CreateServiceAccountCredentialRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateServiceAccountCredentialRequest) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *CreateServiceAccountCredentialRequest) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *CreateServiceAccountCredentialRequest) SetRoleId(v string) {
	o.RoleId = &v
}

func (o CreateServiceAccountCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateServiceAccountCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	return toSerialize, nil
}

type NullableCreateServiceAccountCredentialRequest struct {
	value *CreateServiceAccountCredentialRequest
	isSet bool
}

func (v NullableCreateServiceAccountCredentialRequest) Get() *CreateServiceAccountCredentialRequest {
	return v.value
}

func (v *NullableCreateServiceAccountCredentialRequest) Set(val *CreateServiceAccountCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateServiceAccountCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateServiceAccountCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateServiceAccountCredentialRequest(val *CreateServiceAccountCredentialRequest) *NullableCreateServiceAccountCredentialRequest {
	return &NullableCreateServiceAccountCredentialRequest{value: val, isSet: true}
}

func (v NullableCreateServiceAccountCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateServiceAccountCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


