/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateCustomIdpCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCustomIdpCredentialRequest{}

// CreateCustomIdpCredentialRequest struct for CreateCustomIdpCredentialRequest
type CreateCustomIdpCredentialRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewCreateCustomIdpCredentialRequest instantiates a new CreateCustomIdpCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCustomIdpCredentialRequest() *CreateCustomIdpCredentialRequest {
	this := CreateCustomIdpCredentialRequest{}
	return &this
}

// NewCreateCustomIdpCredentialRequestWithDefaults instantiates a new CreateCustomIdpCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCustomIdpCredentialRequestWithDefaults() *CreateCustomIdpCredentialRequest {
	this := CreateCustomIdpCredentialRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateCustomIdpCredentialRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCustomIdpCredentialRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateCustomIdpCredentialRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateCustomIdpCredentialRequest) SetName(v string) {
	o.Name = &v
}

func (o CreateCustomIdpCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCustomIdpCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateCustomIdpCredentialRequest struct {
	value *CreateCustomIdpCredentialRequest
	isSet bool
}

func (v NullableCreateCustomIdpCredentialRequest) Get() *CreateCustomIdpCredentialRequest {
	return v.value
}

func (v *NullableCreateCustomIdpCredentialRequest) Set(val *CreateCustomIdpCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCustomIdpCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCustomIdpCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCustomIdpCredentialRequest(val *CreateCustomIdpCredentialRequest) *NullableCreateCustomIdpCredentialRequest {
	return &NullableCreateCustomIdpCredentialRequest{value: val, isSet: true}
}

func (v NullableCreateCustomIdpCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCustomIdpCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


