/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateWarehouseWithStorageProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWarehouseWithStorageProfileRequest{}

// CreateWarehouseWithStorageProfileRequest struct for CreateWarehouseWithStorageProfileRequest
type CreateWarehouseWithStorageProfileRequest struct {
	Name *string `json:"name,omitempty"`
	Properties *map[string]string `json:"properties,omitempty"`
}

// NewCreateWarehouseWithStorageProfileRequest instantiates a new CreateWarehouseWithStorageProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWarehouseWithStorageProfileRequest() *CreateWarehouseWithStorageProfileRequest {
	this := CreateWarehouseWithStorageProfileRequest{}
	return &this
}

// NewCreateWarehouseWithStorageProfileRequestWithDefaults instantiates a new CreateWarehouseWithStorageProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWarehouseWithStorageProfileRequestWithDefaults() *CreateWarehouseWithStorageProfileRequest {
	this := CreateWarehouseWithStorageProfileRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateWarehouseWithStorageProfileRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWarehouseWithStorageProfileRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateWarehouseWithStorageProfileRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateWarehouseWithStorageProfileRequest) SetName(v string) {
	o.Name = &v
}

// GetProperties returns the Properties field value if set, zero value otherwise.
func (o *CreateWarehouseWithStorageProfileRequest) GetProperties() map[string]string {
	if o == nil || IsNil(o.Properties) {
		var ret map[string]string
		return ret
	}
	return *o.Properties
}

// GetPropertiesOk returns a tuple with the Properties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWarehouseWithStorageProfileRequest) GetPropertiesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Properties) {
		return nil, false
	}
	return o.Properties, true
}

// HasProperties returns a boolean if a field has been set.
func (o *CreateWarehouseWithStorageProfileRequest) HasProperties() bool {
	if o != nil && !IsNil(o.Properties) {
		return true
	}

	return false
}

// SetProperties gets a reference to the given map[string]string and assigns it to the Properties field.
func (o *CreateWarehouseWithStorageProfileRequest) SetProperties(v map[string]string) {
	o.Properties = &v
}

func (o CreateWarehouseWithStorageProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWarehouseWithStorageProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Properties) {
		toSerialize["properties"] = o.Properties
	}
	return toSerialize, nil
}

type NullableCreateWarehouseWithStorageProfileRequest struct {
	value *CreateWarehouseWithStorageProfileRequest
	isSet bool
}

func (v NullableCreateWarehouseWithStorageProfileRequest) Get() *CreateWarehouseWithStorageProfileRequest {
	return v.value
}

func (v *NullableCreateWarehouseWithStorageProfileRequest) Set(val *CreateWarehouseWithStorageProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWarehouseWithStorageProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWarehouseWithStorageProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWarehouseWithStorageProfileRequest(val *CreateWarehouseWithStorageProfileRequest) *NullableCreateWarehouseWithStorageProfileRequest {
	return &NullableCreateWarehouseWithStorageProfileRequest{value: val, isSet: true}
}

func (v NullableCreateWarehouseWithStorageProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWarehouseWithStorageProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


