/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateCredentialResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCredentialResponse{}

// CreateCredentialResponse struct for CreateCredentialResponse
type CreateCredentialResponse struct {
	Name *string `json:"name,omitempty"`
	CredentialId *string `json:"credentialId,omitempty"`
	CredentialSecret *string `json:"credentialSecret,omitempty"`
}

// NewCreateCredentialResponse instantiates a new CreateCredentialResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCredentialResponse() *CreateCredentialResponse {
	this := CreateCredentialResponse{}
	return &this
}

// NewCreateCredentialResponseWithDefaults instantiates a new CreateCredentialResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCredentialResponseWithDefaults() *CreateCredentialResponse {
	this := CreateCredentialResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateCredentialResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateCredentialResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateCredentialResponse) SetName(v string) {
	o.Name = &v
}

// GetCredentialId returns the CredentialId field value if set, zero value otherwise.
func (o *CreateCredentialResponse) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId) {
		var ret string
		return ret
	}
	return *o.CredentialId
}

// GetCredentialIdOk returns a tuple with the CredentialId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

// HasCredentialId returns a boolean if a field has been set.
func (o *CreateCredentialResponse) HasCredentialId() bool {
	if o != nil && !IsNil(o.CredentialId) {
		return true
	}

	return false
}

// SetCredentialId gets a reference to the given string and assigns it to the CredentialId field.
func (o *CreateCredentialResponse) SetCredentialId(v string) {
	o.CredentialId = &v
}

// GetCredentialSecret returns the CredentialSecret field value if set, zero value otherwise.
func (o *CreateCredentialResponse) GetCredentialSecret() string {
	if o == nil || IsNil(o.CredentialSecret) {
		var ret string
		return ret
	}
	return *o.CredentialSecret
}

// GetCredentialSecretOk returns a tuple with the CredentialSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCredentialResponse) GetCredentialSecretOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialSecret) {
		return nil, false
	}
	return o.CredentialSecret, true
}

// HasCredentialSecret returns a boolean if a field has been set.
func (o *CreateCredentialResponse) HasCredentialSecret() bool {
	if o != nil && !IsNil(o.CredentialSecret) {
		return true
	}

	return false
}

// SetCredentialSecret gets a reference to the given string and assigns it to the CredentialSecret field.
func (o *CreateCredentialResponse) SetCredentialSecret(v string) {
	o.CredentialSecret = &v
}

func (o CreateCredentialResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCredentialResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.CredentialId) {
		toSerialize["credentialId"] = o.CredentialId
	}
	if !IsNil(o.CredentialSecret) {
		toSerialize["credentialSecret"] = o.CredentialSecret
	}
	return toSerialize, nil
}

type NullableCreateCredentialResponse struct {
	value *CreateCredentialResponse
	isSet bool
}

func (v NullableCreateCredentialResponse) Get() *CreateCredentialResponse {
	return v.value
}

func (v *NullableCreateCredentialResponse) Set(val *CreateCredentialResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCredentialResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCredentialResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCredentialResponse(val *CreateCredentialResponse) *NullableCreateCredentialResponse {
	return &NullableCreateCredentialResponse{value: val, isSet: true}
}

func (v NullableCreateCredentialResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCredentialResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


