/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateWarehouseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateWarehouseRequest{}

// CreateWarehouseRequest struct for CreateWarehouseRequest
type CreateWarehouseRequest struct {
	Name *string `json:"name,omitempty"`
	StorageProfileId *string `json:"storageProfileId,omitempty"`
}

// NewCreateWarehouseRequest instantiates a new CreateWarehouseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWarehouseRequest() *CreateWarehouseRequest {
	this := CreateWarehouseRequest{}
	return &this
}

// NewCreateWarehouseRequestWithDefaults instantiates a new CreateWarehouseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWarehouseRequestWithDefaults() *CreateWarehouseRequest {
	this := CreateWarehouseRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateWarehouseRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWarehouseRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateWarehouseRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateWarehouseRequest) SetName(v string) {
	o.Name = &v
}

// GetStorageProfileId returns the StorageProfileId field value if set, zero value otherwise.
func (o *CreateWarehouseRequest) GetStorageProfileId() string {
	if o == nil || IsNil(o.StorageProfileId) {
		var ret string
		return ret
	}
	return *o.StorageProfileId
}

// GetStorageProfileIdOk returns a tuple with the StorageProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWarehouseRequest) GetStorageProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.StorageProfileId) {
		return nil, false
	}
	return o.StorageProfileId, true
}

// HasStorageProfileId returns a boolean if a field has been set.
func (o *CreateWarehouseRequest) HasStorageProfileId() bool {
	if o != nil && !IsNil(o.StorageProfileId) {
		return true
	}

	return false
}

// SetStorageProfileId gets a reference to the given string and assigns it to the StorageProfileId field.
func (o *CreateWarehouseRequest) SetStorageProfileId(v string) {
	o.StorageProfileId = &v
}

func (o CreateWarehouseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateWarehouseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.StorageProfileId) {
		toSerialize["storageProfileId"] = o.StorageProfileId
	}
	return toSerialize, nil
}

type NullableCreateWarehouseRequest struct {
	value *CreateWarehouseRequest
	isSet bool
}

func (v NullableCreateWarehouseRequest) Get() *CreateWarehouseRequest {
	return v.value
}

func (v *NullableCreateWarehouseRequest) Set(val *CreateWarehouseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWarehouseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWarehouseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWarehouseRequest(val *CreateWarehouseRequest) *NullableCreateWarehouseRequest {
	return &NullableCreateWarehouseRequest{value: val, isSet: true}
}

func (v NullableCreateWarehouseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWarehouseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


