/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateMemberCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMemberCredentialRequest{}

// CreateMemberCredentialRequest struct for CreateMemberCredentialRequest
type CreateMemberCredentialRequest struct {
	Name *string `json:"name,omitempty"`
}

// NewCreateMemberCredentialRequest instantiates a new CreateMemberCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMemberCredentialRequest() *CreateMemberCredentialRequest {
	this := CreateMemberCredentialRequest{}
	return &this
}

// NewCreateMemberCredentialRequestWithDefaults instantiates a new CreateMemberCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMemberCredentialRequestWithDefaults() *CreateMemberCredentialRequest {
	this := CreateMemberCredentialRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateMemberCredentialRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMemberCredentialRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateMemberCredentialRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateMemberCredentialRequest) SetName(v string) {
	o.Name = &v
}

func (o CreateMemberCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMemberCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateMemberCredentialRequest struct {
	value *CreateMemberCredentialRequest
	isSet bool
}

func (v NullableCreateMemberCredentialRequest) Get() *CreateMemberCredentialRequest {
	return v.value
}

func (v *NullableCreateMemberCredentialRequest) Set(val *CreateMemberCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMemberCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMemberCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMemberCredentialRequest(val *CreateMemberCredentialRequest) *NullableCreateMemberCredentialRequest {
	return &NullableCreateMemberCredentialRequest{value: val, isSet: true}
}

func (v NullableCreateMemberCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMemberCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


