/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the GetRoleWarehouseGrantsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRoleWarehouseGrantsResponse{}

// GetRoleWarehouseGrantsResponse struct for GetRoleWarehouseGrantsResponse
type GetRoleWarehouseGrantsResponse struct {
	Authorizations []WarehouseAuthorization `json:"authorizations,omitempty"`
}

// NewGetRoleWarehouseGrantsResponse instantiates a new GetRoleWarehouseGrantsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRoleWarehouseGrantsResponse() *GetRoleWarehouseGrantsResponse {
	this := GetRoleWarehouseGrantsResponse{}
	return &this
}

// NewGetRoleWarehouseGrantsResponseWithDefaults instantiates a new GetRoleWarehouseGrantsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRoleWarehouseGrantsResponseWithDefaults() *GetRoleWarehouseGrantsResponse {
	this := GetRoleWarehouseGrantsResponse{}
	return &this
}

// GetAuthorizations returns the Authorizations field value if set, zero value otherwise.
func (o *GetRoleWarehouseGrantsResponse) GetAuthorizations() []WarehouseAuthorization {
	if o == nil || IsNil(o.Authorizations) {
		var ret []WarehouseAuthorization
		return ret
	}
	return o.Authorizations
}

// GetAuthorizationsOk returns a tuple with the Authorizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRoleWarehouseGrantsResponse) GetAuthorizationsOk() ([]WarehouseAuthorization, bool) {
	if o == nil || IsNil(o.Authorizations) {
		return nil, false
	}
	return o.Authorizations, true
}

// HasAuthorizations returns a boolean if a field has been set.
func (o *GetRoleWarehouseGrantsResponse) HasAuthorizations() bool {
	if o != nil && !IsNil(o.Authorizations) {
		return true
	}

	return false
}

// SetAuthorizations gets a reference to the given []WarehouseAuthorization and assigns it to the Authorizations field.
func (o *GetRoleWarehouseGrantsResponse) SetAuthorizations(v []WarehouseAuthorization) {
	o.Authorizations = v
}

func (o GetRoleWarehouseGrantsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRoleWarehouseGrantsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Authorizations) {
		toSerialize["authorizations"] = o.Authorizations
	}
	return toSerialize, nil
}

type NullableGetRoleWarehouseGrantsResponse struct {
	value *GetRoleWarehouseGrantsResponse
	isSet bool
}

func (v NullableGetRoleWarehouseGrantsResponse) Get() *GetRoleWarehouseGrantsResponse {
	return v.value
}

func (v *NullableGetRoleWarehouseGrantsResponse) Set(val *GetRoleWarehouseGrantsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRoleWarehouseGrantsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRoleWarehouseGrantsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRoleWarehouseGrantsResponse(val *GetRoleWarehouseGrantsResponse) *NullableGetRoleWarehouseGrantsResponse {
	return &NullableGetRoleWarehouseGrantsResponse{value: val, isSet: true}
}

func (v NullableGetRoleWarehouseGrantsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRoleWarehouseGrantsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


