/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateIamRoleMappingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIamRoleMappingRequest{}

// CreateIamRoleMappingRequest struct for CreateIamRoleMappingRequest
type CreateIamRoleMappingRequest struct {
	Name *string `json:"name,omitempty"`
	AwsRoleArn *string `json:"awsRoleArn,omitempty"`
	RoleId *string `json:"roleId,omitempty"`
}

// NewCreateIamRoleMappingRequest instantiates a new CreateIamRoleMappingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIamRoleMappingRequest() *CreateIamRoleMappingRequest {
	this := CreateIamRoleMappingRequest{}
	return &this
}

// NewCreateIamRoleMappingRequestWithDefaults instantiates a new CreateIamRoleMappingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIamRoleMappingRequestWithDefaults() *CreateIamRoleMappingRequest {
	this := CreateIamRoleMappingRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateIamRoleMappingRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIamRoleMappingRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateIamRoleMappingRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateIamRoleMappingRequest) SetName(v string) {
	o.Name = &v
}

// GetAwsRoleArn returns the AwsRoleArn field value if set, zero value otherwise.
func (o *CreateIamRoleMappingRequest) GetAwsRoleArn() string {
	if o == nil || IsNil(o.AwsRoleArn) {
		var ret string
		return ret
	}
	return *o.AwsRoleArn
}

// GetAwsRoleArnOk returns a tuple with the AwsRoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIamRoleMappingRequest) GetAwsRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.AwsRoleArn) {
		return nil, false
	}
	return o.AwsRoleArn, true
}

// HasAwsRoleArn returns a boolean if a field has been set.
func (o *CreateIamRoleMappingRequest) HasAwsRoleArn() bool {
	if o != nil && !IsNil(o.AwsRoleArn) {
		return true
	}

	return false
}

// SetAwsRoleArn gets a reference to the given string and assigns it to the AwsRoleArn field.
func (o *CreateIamRoleMappingRequest) SetAwsRoleArn(v string) {
	o.AwsRoleArn = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *CreateIamRoleMappingRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateIamRoleMappingRequest) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *CreateIamRoleMappingRequest) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *CreateIamRoleMappingRequest) SetRoleId(v string) {
	o.RoleId = &v
}

func (o CreateIamRoleMappingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIamRoleMappingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AwsRoleArn) {
		toSerialize["awsRoleArn"] = o.AwsRoleArn
	}
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	return toSerialize, nil
}

type NullableCreateIamRoleMappingRequest struct {
	value *CreateIamRoleMappingRequest
	isSet bool
}

func (v NullableCreateIamRoleMappingRequest) Get() *CreateIamRoleMappingRequest {
	return v.value
}

func (v *NullableCreateIamRoleMappingRequest) Set(val *CreateIamRoleMappingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIamRoleMappingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIamRoleMappingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIamRoleMappingRequest(val *CreateIamRoleMappingRequest) *NullableCreateIamRoleMappingRequest {
	return &NullableCreateIamRoleMappingRequest{value: val, isSet: true}
}

func (v NullableCreateIamRoleMappingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIamRoleMappingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


