/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateS3StorageProfileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateS3StorageProfileRequest{}

// CreateS3StorageProfileRequest struct for CreateS3StorageProfileRequest
type CreateS3StorageProfileRequest struct {
	Region *string `json:"region,omitempty"`
	Bucket *string `json:"bucket,omitempty"`
	RoleArn *string `json:"roleArn,omitempty"`
}

// NewCreateS3StorageProfileRequest instantiates a new CreateS3StorageProfileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateS3StorageProfileRequest() *CreateS3StorageProfileRequest {
	this := CreateS3StorageProfileRequest{}
	return &this
}

// NewCreateS3StorageProfileRequestWithDefaults instantiates a new CreateS3StorageProfileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateS3StorageProfileRequestWithDefaults() *CreateS3StorageProfileRequest {
	this := CreateS3StorageProfileRequest{}
	return &this
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *CreateS3StorageProfileRequest) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateS3StorageProfileRequest) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *CreateS3StorageProfileRequest) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *CreateS3StorageProfileRequest) SetRegion(v string) {
	o.Region = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *CreateS3StorageProfileRequest) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateS3StorageProfileRequest) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *CreateS3StorageProfileRequest) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *CreateS3StorageProfileRequest) SetBucket(v string) {
	o.Bucket = &v
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *CreateS3StorageProfileRequest) GetRoleArn() string {
	if o == nil || IsNil(o.RoleArn) {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateS3StorageProfileRequest) GetRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.RoleArn) {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *CreateS3StorageProfileRequest) HasRoleArn() bool {
	if o != nil && !IsNil(o.RoleArn) {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *CreateS3StorageProfileRequest) SetRoleArn(v string) {
	o.RoleArn = &v
}

func (o CreateS3StorageProfileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateS3StorageProfileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.RoleArn) {
		toSerialize["roleArn"] = o.RoleArn
	}
	return toSerialize, nil
}

type NullableCreateS3StorageProfileRequest struct {
	value *CreateS3StorageProfileRequest
	isSet bool
}

func (v NullableCreateS3StorageProfileRequest) Get() *CreateS3StorageProfileRequest {
	return v.value
}

func (v *NullableCreateS3StorageProfileRequest) Set(val *CreateS3StorageProfileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateS3StorageProfileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateS3StorageProfileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateS3StorageProfileRequest(val *CreateS3StorageProfileRequest) *NullableCreateS3StorageProfileRequest {
	return &NullableCreateS3StorageProfileRequest{value: val, isSet: true}
}

func (v NullableCreateS3StorageProfileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateS3StorageProfileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


