/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the CreateOidcCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOidcCredentialRequest{}

// CreateOidcCredentialRequest struct for CreateOidcCredentialRequest
type CreateOidcCredentialRequest struct {
	Name *string `json:"name,omitempty"`
	OidcIssuer *string `json:"oidcIssuer,omitempty"`
	OidcClaimKey *string `json:"oidcClaimKey,omitempty"`
	OidcClaimValue *string `json:"oidcClaimValue,omitempty"`
	RoleId *string `json:"roleId,omitempty"`
}

// NewCreateOidcCredentialRequest instantiates a new CreateOidcCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOidcCredentialRequest() *CreateOidcCredentialRequest {
	this := CreateOidcCredentialRequest{}
	return &this
}

// NewCreateOidcCredentialRequestWithDefaults instantiates a new CreateOidcCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOidcCredentialRequestWithDefaults() *CreateOidcCredentialRequest {
	this := CreateOidcCredentialRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateOidcCredentialRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOidcCredentialRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateOidcCredentialRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateOidcCredentialRequest) SetName(v string) {
	o.Name = &v
}

// GetOidcIssuer returns the OidcIssuer field value if set, zero value otherwise.
func (o *CreateOidcCredentialRequest) GetOidcIssuer() string {
	if o == nil || IsNil(o.OidcIssuer) {
		var ret string
		return ret
	}
	return *o.OidcIssuer
}

// GetOidcIssuerOk returns a tuple with the OidcIssuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOidcCredentialRequest) GetOidcIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.OidcIssuer) {
		return nil, false
	}
	return o.OidcIssuer, true
}

// HasOidcIssuer returns a boolean if a field has been set.
func (o *CreateOidcCredentialRequest) HasOidcIssuer() bool {
	if o != nil && !IsNil(o.OidcIssuer) {
		return true
	}

	return false
}

// SetOidcIssuer gets a reference to the given string and assigns it to the OidcIssuer field.
func (o *CreateOidcCredentialRequest) SetOidcIssuer(v string) {
	o.OidcIssuer = &v
}

// GetOidcClaimKey returns the OidcClaimKey field value if set, zero value otherwise.
func (o *CreateOidcCredentialRequest) GetOidcClaimKey() string {
	if o == nil || IsNil(o.OidcClaimKey) {
		var ret string
		return ret
	}
	return *o.OidcClaimKey
}

// GetOidcClaimKeyOk returns a tuple with the OidcClaimKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOidcCredentialRequest) GetOidcClaimKeyOk() (*string, bool) {
	if o == nil || IsNil(o.OidcClaimKey) {
		return nil, false
	}
	return o.OidcClaimKey, true
}

// HasOidcClaimKey returns a boolean if a field has been set.
func (o *CreateOidcCredentialRequest) HasOidcClaimKey() bool {
	if o != nil && !IsNil(o.OidcClaimKey) {
		return true
	}

	return false
}

// SetOidcClaimKey gets a reference to the given string and assigns it to the OidcClaimKey field.
func (o *CreateOidcCredentialRequest) SetOidcClaimKey(v string) {
	o.OidcClaimKey = &v
}

// GetOidcClaimValue returns the OidcClaimValue field value if set, zero value otherwise.
func (o *CreateOidcCredentialRequest) GetOidcClaimValue() string {
	if o == nil || IsNil(o.OidcClaimValue) {
		var ret string
		return ret
	}
	return *o.OidcClaimValue
}

// GetOidcClaimValueOk returns a tuple with the OidcClaimValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOidcCredentialRequest) GetOidcClaimValueOk() (*string, bool) {
	if o == nil || IsNil(o.OidcClaimValue) {
		return nil, false
	}
	return o.OidcClaimValue, true
}

// HasOidcClaimValue returns a boolean if a field has been set.
func (o *CreateOidcCredentialRequest) HasOidcClaimValue() bool {
	if o != nil && !IsNil(o.OidcClaimValue) {
		return true
	}

	return false
}

// SetOidcClaimValue gets a reference to the given string and assigns it to the OidcClaimValue field.
func (o *CreateOidcCredentialRequest) SetOidcClaimValue(v string) {
	o.OidcClaimValue = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *CreateOidcCredentialRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOidcCredentialRequest) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *CreateOidcCredentialRequest) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *CreateOidcCredentialRequest) SetRoleId(v string) {
	o.RoleId = &v
}

func (o CreateOidcCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOidcCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.OidcIssuer) {
		toSerialize["oidcIssuer"] = o.OidcIssuer
	}
	if !IsNil(o.OidcClaimKey) {
		toSerialize["oidcClaimKey"] = o.OidcClaimKey
	}
	if !IsNil(o.OidcClaimValue) {
		toSerialize["oidcClaimValue"] = o.OidcClaimValue
	}
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	return toSerialize, nil
}

type NullableCreateOidcCredentialRequest struct {
	value *CreateOidcCredentialRequest
	isSet bool
}

func (v NullableCreateOidcCredentialRequest) Get() *CreateOidcCredentialRequest {
	return v.value
}

func (v *NullableCreateOidcCredentialRequest) Set(val *CreateOidcCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOidcCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOidcCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOidcCredentialRequest(val *CreateOidcCredentialRequest) *NullableCreateOidcCredentialRequest {
	return &NullableCreateOidcCredentialRequest{value: val, isSet: true}
}

func (v NullableCreateOidcCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOidcCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


