/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tabular

import (
	"encoding/json"
)

// checks if the MemberRef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberRef{}

// MemberRef struct for MemberRef
type MemberRef struct {
	Id *string `json:"id,omitempty"`
	Email *string `json:"email,omitempty"`
}

// NewMemberRef instantiates a new MemberRef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberRef() *MemberRef {
	this := MemberRef{}
	return &this
}

// NewMemberRefWithDefaults instantiates a new MemberRef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberRefWithDefaults() *MemberRef {
	this := MemberRef{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MemberRef) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberRef) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MemberRef) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MemberRef) SetId(v string) {
	o.Id = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *MemberRef) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberRef) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *MemberRef) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *MemberRef) SetEmail(v string) {
	o.Email = &v
}

func (o MemberRef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberRef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	return toSerialize, nil
}

type NullableMemberRef struct {
	value *MemberRef
	isSet bool
}

func (v NullableMemberRef) Get() *MemberRef {
	return v.value
}

func (v *NullableMemberRef) Set(val *MemberRef) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberRef) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberRef(val *MemberRef) *NullableMemberRef {
	return &NullableMemberRef{value: val, isSet: true}
}

func (v NullableMemberRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


